version: '3'

services:
  controller:
    container_name: controller
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - manipulator
      - mongo_db
    env_file:
      - ".env"
    command: --controller
    ports:
      - "8000:8000"

  manipulator:
    container_name: manipulator
    build:
      context: .
      dockerfile: Dockerfile
    command: --manipulator
    env_file:
      - ".env"

  sensor:
    container_name: sensor
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - controller
    command: --sensor
    env_file:
      - ".env"

  mongo_db:
    container_name: ${MONGO_HOST}
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: --quiet --logpath /dev/null
    restart: unless-stopped
    volumes:
      - storage:/data/db:rw

volumes:
  storage:
    driver: local
