version: '3'

services:
  controller:
    container_name: controller
    build:
      context: .
      dockerfile: Dockerfile
    command: --controller

  manipulator:
    container_name: manipulator
    build:
      context: .
      dockerfile: Dockerfile
    command: --manipulator

  sensor:
    container_name: sensor
    build:
      context: .
      dockerfile: Dockerfile
    command: --sensor
