version: '3'

x-sensor: &sensor
  build:
    context: .
    dockerfile: Dockerfile
  command: --sensor
  restart: on-failure
  depends_on:
    - controller
  env_file:
    - ".env"

services:
  controller:
    container_name: controller
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - manipulator
      - mongo_db
    restart: on-failure
    env_file:
      - ".env"
    command: --controller
    ports:
      - "8000:8000"

  manipulator:
    container_name: manipulator
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    command: --manipulator
    env_file:
      - ".env"

  sensor1:
    container_name: sensor1
    <<: *sensor

  sensor2:
    container_name: sensor2
    <<: *sensor

  sensor3:
    container_name: sensor3
    <<: *sensor

  sensor4:
    container_name: sensor4
    <<: *sensor

  sensor5:
    container_name: sensor5
    <<: *sensor

  sensor6:
    container_name: sensor6
    <<: *sensor

  sensor7:
    container_name: sensor7
    <<: *sensor

  sensor8:
    container_name: sensor8
    <<: *sensor

  mongo_db:
    container_name: ${MONGO_HOST}
    image: 'mongo'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    command: --quiet --logpath /dev/null
    restart: unless-stopped
    volumes:
      - storage:/data/db:rw

volumes:
  storage:
    driver: local
